export const DEFAULT_CATEGORIES = [
  { name: "Paycheck",         color: "#22c55e", icon: "Banknote",        is_income: true  },
  { name: "Freelance",        color: "#16a34a", icon: "Laptop",          is_income: true  },
  { name: "Investment Return",color: "#15803d", icon: "TrendingUp",      is_income: true  },
  { name: "Reimbursement",    color: "#4ade80", icon: "RotateCcw",       is_income: true  },
  { name: "Rent/Mortgage",    color: "#6366f1", icon: "House",           is_income: false },
  { name: "Utilities",        color: "#818cf8", icon: "Zap",             is_income: false },
  { name: "Internet/Phone",   color: "#a5b4fc", icon: "Wifi",            is_income: false },
  { name: "Groceries",        color: "#f97316", icon: "ShoppingCart",    is_income: false },
  { name: "Restaurants",      color: "#fb923c", icon: "UtensilsCrossed", is_income: false },
  { name: "Coffee",           color: "#c2410c", icon: "Coffee",          is_income: false },
  { name: "Gas",              color: "#eab308", icon: "Fuel",            is_income: false },
  { name: "Public Transit",   color: "#fbbf24", icon: "Bus",             is_income: false },
  { name: "Rideshare",        color: "#d97706", icon: "Car",             is_income: false },
  { name: "Medical",          color: "#ef4444", icon: "HeartPulse",      is_income: false },
  { name: "Pharmacy",         color: "#f87171", icon: "Pill",            is_income: false },
  { name: "Fitness",          color: "#dc2626", icon: "Dumbbell",        is_income: false },
  { name: "Clothing",         color: "#ec4899", icon: "ShoppingBag",     is_income: false },
  { name: "Electronics",      color: "#db2777", icon: "Monitor",         is_income: false },
  { name: "Online Shopping",  color: "#be185d", icon: "Package",         is_income: false },
  { name: "Streaming",        color: "#8b5cf6", icon: "Play",            is_income: false },
  { name: "Games",            color: "#7c3aed", icon: "Gamepad2",        is_income: false },
  { name: "Subscriptions",    color: "#0ea5e9", icon: "RefreshCw",       is_income: false },
  { name: "Insurance",        color: "#0284c7", icon: "Shield",          is_income: false },
  { name: "Bank Fees",        color: "#075985", icon: "Landmark",        is_income: false },
  { name: "Taxes",            color: "#0c4a6e", icon: "Receipt",         is_income: false },
  { name: "Travel",           color: "#14b8a6", icon: "Plane",           is_income: false },
  { name: "Gifts",            color: "#06b6d4", icon: "Gift",            is_income: false },
  { name: "Education",        color: "#10b981", icon: "GraduationCap",   is_income: false },
  { name: "Uncategorized",    color: "#6b7280", icon: "CircleHelp",      is_income: false },
];

export const ACCOUNT_TYPES = ["checking", "savings", "credit", "investment", "cash", "loan"];
export const BUDGET_PERIODS = ["monthly", "weekly", "yearly"];
